# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_book.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_book.proto',
  package='MARS',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64\x61ta_book.proto\x12\x04MARS\"\xa9\x03\n\x05\x41gent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\x05shape\x18\x02 \x01(\x0b\x32\x0c.MARS.Vector\x12%\n\x0flinear_velocity\x18\x03 \x01(\x0b\x32\x0c.MARS.Vector\x12\x18\n\x10\x61ngular_velocity\x18\x04 \x01(\x02\x12\r\n\x05\x61ngle\x18\x05 \x01(\x02\x12\x1d\n\x08position\x18\x06 \x01(\x0b\x32\x0b.MARS.Point\x12)\n\x14\x64\x65stination_location\x18\x07 \x01(\x0b\x32\x0b.MARS.Point\x12)\n\rlocal_planner\x18\x08 \x01(\x0b\x32\x12.MARS.LocalPlanner\x12+\n\x0eglobal_planner\x18\t \x01(\x0b\x32\x13.MARS.GlobalPlanner\x12\x1c\n\x06sensor\x18\n \x01(\x0b\x32\x0c.MARS.Sensor\x12\x17\n\x0fray_length_list\x18\x0b \x03(\x02\x12&\n\x11sequence_of_poses\x18\x0c \x03(\x0b\x32\x0b.MARS.Point\x12&\n\x11internal_stations\x18\r \x03(\x0b\x32\x0b.MARS.Point\"\x1c\n\x0cLocalPlanner\x12\x0c\n\x04type\x18\x01 \x01(\t\"\x84\x01\n\rGlobalPlanner\x12\x0c\n\x04type\x18\x01 \x01(\t\x12-\n\x08map_type\x18\x02 \x01(\x0e\x32\x1b.MARS.GlobalPlanner.MapType\x12\x11\n\tagents_id\x18\x03 \x03(\x05\"#\n\x07MapType\x12\x08\n\x04GRID\x10\x00\x12\x0e\n\nCONTINUOUS\x10\x01\"\x98\x01\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06radius\x18\x02 \x01(\x02\x12\r\n\x05\x61ngle\x18\x03 \x01(\x02\x12\x1d\n\x08location\x18\x04 \x01(\x0b\x32\x0b.MARS.Point\x12\x19\n\x11visible_agents_id\x18\x05 \x03(\x05\x12)\n\x11visible_obstacles\x18\x06 \x03(\x0b\x32\x0e.MARS.Obstacle\"V\n\x08Obstacle\x12\x1b\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x0b.MARS.Point\x12\x1f\n\tdimension\x18\x02 \x01(\x0b\x32\x0c.MARS.Vector\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x1e\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x62\x06proto3')
)



_GLOBALPLANNER_MAPTYPE = _descriptor.EnumDescriptor(
  name='MapType',
  full_name='MARS.GlobalPlanner.MapType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GRID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUOUS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=581,
  serialized_end=616,
)
_sym_db.RegisterEnumDescriptor(_GLOBALPLANNER_MAPTYPE)


_AGENT = _descriptor.Descriptor(
  name='Agent',
  full_name='MARS.Agent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MARS.Agent.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='MARS.Agent.shape', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='MARS.Agent.linear_velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='MARS.Agent.angular_velocity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='MARS.Agent.angle', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='MARS.Agent.position', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_location', full_name='MARS.Agent.destination_location', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_planner', full_name='MARS.Agent.local_planner', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_planner', full_name='MARS.Agent.global_planner', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='MARS.Agent.sensor', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ray_length_list', full_name='MARS.Agent.ray_length_list', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence_of_poses', full_name='MARS.Agent.sequence_of_poses', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='internal_stations', full_name='MARS.Agent.internal_stations', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=451,
)


_LOCALPLANNER = _descriptor.Descriptor(
  name='LocalPlanner',
  full_name='MARS.LocalPlanner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MARS.LocalPlanner.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=481,
)


_GLOBALPLANNER = _descriptor.Descriptor(
  name='GlobalPlanner',
  full_name='MARS.GlobalPlanner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MARS.GlobalPlanner.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_type', full_name='MARS.GlobalPlanner.map_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agents_id', full_name='MARS.GlobalPlanner.agents_id', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GLOBALPLANNER_MAPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=616,
)


_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='MARS.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MARS.Sensor.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='MARS.Sensor.radius', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='MARS.Sensor.angle', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='MARS.Sensor.location', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visible_agents_id', full_name='MARS.Sensor.visible_agents_id', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visible_obstacles', full_name='MARS.Sensor.visible_obstacles', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=771,
)


_OBSTACLE = _descriptor.Descriptor(
  name='Obstacle',
  full_name='MARS.Obstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='center', full_name='MARS.Obstacle.center', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimension', full_name='MARS.Obstacle.dimension', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='MARS.Obstacle.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=859,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='MARS.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MARS.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='MARS.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=861,
  serialized_end=890,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='MARS.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MARS.Vector.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='MARS.Vector.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=892,
  serialized_end=922,
)

_AGENT.fields_by_name['shape'].message_type = _VECTOR
_AGENT.fields_by_name['linear_velocity'].message_type = _VECTOR
_AGENT.fields_by_name['position'].message_type = _POINT
_AGENT.fields_by_name['destination_location'].message_type = _POINT
_AGENT.fields_by_name['local_planner'].message_type = _LOCALPLANNER
_AGENT.fields_by_name['global_planner'].message_type = _GLOBALPLANNER
_AGENT.fields_by_name['sensor'].message_type = _SENSOR
_AGENT.fields_by_name['sequence_of_poses'].message_type = _POINT
_AGENT.fields_by_name['internal_stations'].message_type = _POINT
_GLOBALPLANNER.fields_by_name['map_type'].enum_type = _GLOBALPLANNER_MAPTYPE
_GLOBALPLANNER_MAPTYPE.containing_type = _GLOBALPLANNER
_SENSOR.fields_by_name['location'].message_type = _POINT
_SENSOR.fields_by_name['visible_obstacles'].message_type = _OBSTACLE
_OBSTACLE.fields_by_name['center'].message_type = _POINT
_OBSTACLE.fields_by_name['dimension'].message_type = _VECTOR
DESCRIPTOR.message_types_by_name['Agent'] = _AGENT
DESCRIPTOR.message_types_by_name['LocalPlanner'] = _LOCALPLANNER
DESCRIPTOR.message_types_by_name['GlobalPlanner'] = _GLOBALPLANNER
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['Obstacle'] = _OBSTACLE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), dict(
  DESCRIPTOR = _AGENT,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.Agent)
  ))
_sym_db.RegisterMessage(Agent)

LocalPlanner = _reflection.GeneratedProtocolMessageType('LocalPlanner', (_message.Message,), dict(
  DESCRIPTOR = _LOCALPLANNER,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.LocalPlanner)
  ))
_sym_db.RegisterMessage(LocalPlanner)

GlobalPlanner = _reflection.GeneratedProtocolMessageType('GlobalPlanner', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALPLANNER,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.GlobalPlanner)
  ))
_sym_db.RegisterMessage(GlobalPlanner)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.Sensor)
  ))
_sym_db.RegisterMessage(Sensor)

Obstacle = _reflection.GeneratedProtocolMessageType('Obstacle', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLE,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.Obstacle)
  ))
_sym_db.RegisterMessage(Obstacle)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.Point)
  ))
_sym_db.RegisterMessage(Point)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'data_book_pb2'
  # @@protoc_insertion_point(class_scope:MARS.Vector)
  ))
_sym_db.RegisterMessage(Vector)


# @@protoc_insertion_point(module_scope)
